export const COOKIE_PREFIX = "trellis";
export const SESSION_TOKEN_COOKIE_SUFFIX = "session_token";
export const SESSION_TOKEN_COOKIE = `${COOKIE_PREFIX}.${SESSION_TOKEN_COOKIE_SUFFIX}`;
export const SESSION_DATA_COOKIE_SUFFIX = "session_data";
export const SESSION_DATA_COOKIE = `${COOKIE_PREFIX}.${SESSION_DATA_COOKIE_SUFFIX}`;
export const DONT_REMEMBER_COOKIE_SUFFIX = "dont_remember";
export const DONT_REMEMBER_COOKIE = `${COOKIE_PREFIX}.${DONT_REMEMBER_COOKIE_SUFFIX}`;

export const MIN_PASSWORD_LENGTH = 12;
export const MAX_PASSWORD_LENGTH = 128;
