/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route";
import { Route as R500IndexRouteImport } from "./routes/500/index";
import { Route as authSignInIndexRouteImport } from "./routes/(auth)/sign-in/index";
import { Route as AuthenticatedAccountIndexRouteImport } from "./routes/_authenticated/account/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const R500IndexRoute = R500IndexRouteImport.update({
  id: "/500/",
  path: "/500/",
  getParentRoute: () => rootRouteImport,
} as any);
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: "/(auth)/sign-in/",
  path: "/sign-in/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: "/account/",
    path: "/account/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/500/": typeof R500IndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/sign-in/": typeof authSignInIndexRoute;
  "/account/": typeof AuthenticatedAccountIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/500": typeof R500IndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/sign-in": typeof authSignInIndexRoute;
  "/account": typeof AuthenticatedAccountIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/500/": typeof R500IndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/(auth)/sign-in/": typeof authSignInIndexRoute;
  "/_authenticated/account/": typeof AuthenticatedAccountIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/500/" | "/api/auth/$" | "/sign-in/" | "/account/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/500" | "/api/auth/$" | "/sign-in" | "/account";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/500/"
    | "/api/auth/$"
    | "/(auth)/sign-in/"
    | "/_authenticated/account/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  R500IndexRoute: typeof R500IndexRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  authSignInIndexRoute: typeof authSignInIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/500/": {
      id: "/500/";
      path: "/500";
      fullPath: "/500/";
      preLoaderRoute: typeof R500IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/sign-in/": {
      id: "/(auth)/sign-in/";
      path: "/sign-in";
      fullPath: "/sign-in/";
      preLoaderRoute: typeof authSignInIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/account/": {
      id: "/_authenticated/account/";
      path: "/account";
      fullPath: "/account/";
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R500IndexRoute: R500IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  authSignInIndexRoute: authSignInIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.ts";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
